import type { ParsedArticle } from '../../types'

export const mockArticle: ParsedArticle = {
  title: '静勝軒与江戸城眺望',
  paragraphs: [
    {
      originalText:
        'むかし太田道灌が始めて江戸城を築いた時、城上に間燕の室を置て之これを静勝軒と名付け、東は江戸湾を望み西は富士秩父の連嶺を軒端に眺めた所から、東を泊船亭と曰いい西を含雪斎と曰うたとのことである。静勝軒を題として記述した詩文に、「西嶺当レ※(「窗／心」、第3水準1-89-54)雪界レ天」、又は「西望則逾二原野一而雪嶺界レ天」とある句は、蓋けだし実景をよんだもので、雪嶺或は西嶺は富士山を指したものに外なるまい。道灌は風流二千石といわれた程あって、歌も上手によみ、扇谷の老臣として軍旅に忙しい身でありながら、よくこの静勝軒で歌合や連歌の会などを催した。元より泊船亭や含雪斎の名は、「※(「窗／心」、第3水準1-89-54)含二西嶺千秋雪一、門泊二東呉万里船一」という詩句から取ったものであろうが、当時の江戸城は今の宮城内に在る元の本丸の地であったということであるから、眺望の広闊なることは言う迄もないことで、富士は更なり遠い赤石山脈の悪沢わるさわ岳や荒川岳（塩見岳）の七月上旬に於ける残雪は、恐らく含雪斎の主人公をして、西嶺千秋雪の感を深からしめたことであろうと思う。',
      sentences: [
        {
          originalText:
            'むかし太田道灌が始めて江戸城を築いた時、城上に間燕の室を置て之これを静勝軒と名付け、東は江戸湾を望み西は富士秩父の連嶺を軒端に眺めた所から、東を泊船亭と曰いい西を含雪斎と曰うたとのことである。',
          translation:
            '从前太田道灌初建江户城时，在城上设置一间名为“静胜轩”的房室；因其东望江户湾、西眺富士与秩父连峰，故又把东侧称作泊船亭，西侧称作含雪斋。',
          tokens: [
            { surface: 'むかし', lemma: 'むかし', reading: 'ムカシ', furigana: 'むかし', pos: '副詞', meaning: '从前，往昔' },
            { surface: '太田道灌', lemma: '太田道灌', reading: 'オオタドウカン', furigana: 'おおたどうかん', pos: '名詞', meaning: '室町时代武将太田道灌' },
            { surface: 'が', lemma: 'が', reading: 'ガ', furigana: 'が', pos: '助詞', meaning: '主格助词' },
            {
              surface: '始めて',
              lemma: '始める',
              reading: 'ハジメテ',
              furigana: 'はじめて',
              pos: '動詞',
              meaning: '初次开始',
              conjugation: { type: '一段', form: '連用形A' },
            },
            { surface: '江戸城', lemma: '江戸城', reading: 'エドジョウ', furigana: 'えどじょう', pos: '名詞', meaning: '江户城' },
            { surface: 'を', lemma: 'を', reading: 'ヲ', furigana: 'を', pos: '助詞', meaning: '宾格助词' },
            {
              surface: '築いた',
              lemma: '築く',
              reading: 'キズイタ',
              furigana: 'きずいた',
              pos: '動詞',
              meaning: '建造',
              conjugation: { type: '五段', form: '連体形' },
            },
            { surface: '時', lemma: '時', reading: 'トキ', furigana: 'とき', pos: '名詞', meaning: '时候' },
            { surface: '、', lemma: '、', reading: '、', furigana: '、', pos: '接尾辞', meaning: '顿号' },
            { surface: '城上', lemma: '城上', reading: 'ジョウジョウ', furigana: 'じょうじょう', pos: '名詞', meaning: '城楼之上' },
            { surface: 'に', lemma: 'に', reading: 'ニ', furigana: 'に', pos: '助詞', meaning: '地点助词' },
            { surface: '間燕の室', lemma: '間燕の室', reading: 'カンエンノシツ', furigana: 'かんえんのしつ', pos: '名詞', meaning: '一间室屋' },
            {
              surface: 'を置て',
              lemma: '置く',
              reading: 'ヲイテ',
              furigana: 'おいて',
              pos: '動詞',
              meaning: '设置，安置',
              conjugation: { type: '五段', form: '連用形B' },
            },
            { surface: '之これを', lemma: '之', reading: 'コレヲ', furigana: 'これを', pos: '代名詞', meaning: '把这个' },
            {
              surface: '静勝軒',
              lemma: '静勝軒',
              reading: 'セイショウケン',
              furigana: 'せいしょうけん',
              pos: '名詞',
              meaning: '静胜轩',
            },
            {
              surface: 'と名付け',
              lemma: '名付ける',
              reading: 'トナヅケ',
              furigana: 'となづけ',
              pos: '動詞',
              meaning: '命名为',
              conjugation: { type: '一段', form: '連用形A' },
            },
            { surface: '、', lemma: '、', reading: '、', furigana: '、', pos: '接尾辞', meaning: '顿号' },
            { surface: '東は', lemma: '東', reading: 'ヒガシハ', furigana: 'ひがしは', pos: '名詞', meaning: '东面则' },
            { surface: '江戸湾', lemma: '江戸湾', reading: 'エドワン', furigana: 'えどわん', pos: '名詞', meaning: '江户湾' },
            { surface: 'を', lemma: 'を', reading: 'ヲ', furigana: 'を', pos: '助詞', meaning: '宾格助词' },
            {
              surface: '望み',
              lemma: '望む',
              reading: 'ノゾミ',
              furigana: 'のぞみ',
              pos: '動詞',
              meaning: '眺望',
              conjugation: { type: '五段', form: '連用形A' },
            },
            { surface: '西は', lemma: '西', reading: 'ニシハ', furigana: 'にしは', pos: '名詞', meaning: '西面则' },
            { surface: '富士秩父の連嶺', lemma: '富士秩父の連嶺', reading: 'フジチチブノレンレイ', furigana: 'ふじちちぶのれんれい', pos: '名詞', meaning: '富士与秩父山脉连峰' },
            { surface: 'を', lemma: 'を', reading: 'ヲ', furigana: 'を', pos: '助詞', meaning: '宾格助词' },
            { surface: '軒端', lemma: '軒端', reading: 'ノキバ', furigana: 'のきば', pos: '名詞', meaning: '檐边' },
            { surface: 'に', lemma: 'に', reading: 'ニ', furigana: 'に', pos: '助詞', meaning: '地点助词' },
            {
              surface: '眺めた',
              lemma: '眺める',
              reading: 'ナガメタ',
              furigana: 'ながめた',
              pos: '動詞',
              meaning: '眺望',
              conjugation: { type: '一段', form: '連体形' },
            },
            { surface: '所から', lemma: '所', reading: 'トコロカラ', furigana: 'ところから', pos: '名詞', meaning: '由于此处' },
            { surface: '、', lemma: '、', reading: '、', furigana: '、', pos: '接尾辞', meaning: '顿号' },
            { surface: '東を泊船亭', lemma: '泊船亭', reading: 'トウヲハクセンテイ', furigana: 'ひがしをはくせんてい', pos: '名詞', meaning: '东侧称泊船亭' },
            { surface: 'と曰いい', lemma: '曰う', reading: 'トイイ', furigana: 'といい', pos: '動詞', meaning: '称作', conjugation: { type: '五段', form: '連用形A' } },
            { surface: '西を含雪斎', lemma: '含雪斎', reading: 'ニシヲガンセツサイ', furigana: 'にしをがんせつさい', pos: '名詞', meaning: '西侧称含雪斋' },
            { surface: 'と曰うた', lemma: '曰う', reading: 'トイウタ', furigana: 'というた', pos: '動詞', meaning: '称作', conjugation: { type: '五段', form: '連体形' } },
            { surface: 'とのことである', lemma: 'こと', reading: 'トノコトデアル', furigana: 'とのことである', pos: '名詞', meaning: '据说如此' },
            { surface: '。', lemma: '。', reading: '。', furigana: '。', pos: '接尾辞', meaning: '句号' },
          ],
          grammarTips: [
            { point: '〜時', description: '用作时间从句，交代主要叙述发生的背景时间。', difficulty: 'beginner', tokenIndices: [3, 4, 5, 6, 7] },
            { point: '〜とのことである', description: '书面转述表达，相当于“据说……”“文献记载……”。', difficulty: 'intermediate', tokenIndices: [33] },
          ],
          dependencyTree: {
            text: '太田道灌が江戸城築造时的命名与眺望说明',
            tokenIndices: Array.from({ length: 35 }, (_, index) => index),
            relation: 'root',
            children: [
              { text: 'むかし太田道灌が始めて江戸城を築いた時', tokenIndices: [0, 1, 2, 3, 4, 5, 6, 7], relation: 'advmod', children: [] },
              { text: '城上に間燕の室を置て之これを静勝軒と名付け', tokenIndices: [9, 10, 11, 12, 13, 14, 15], relation: 'conj', children: [] },
              { text: '東は江戸湾を望み', tokenIndices: [17, 18, 19, 20], relation: 'conj', children: [] },
              { text: '西は富士秩父の連嶺を軒端に眺めた所から', tokenIndices: [21, 22, 23, 24, 25, 26, 27], relation: 'advmod', children: [] },
              { text: '東を泊船亭と曰いい西を含雪斎と曰うた', tokenIndices: [29, 30, 31, 32], relation: 'conj', children: [] },
              { text: 'とのことである', tokenIndices: [33], relation: 'aux', children: [] },
              { text: '。', tokenIndices: [34], relation: 'punct', children: [] },
            ],
          },
        },
        {
          originalText:
            '静勝軒を題として記述した詩文に、「西嶺当レ※(「窗／心」、第3水準1-89-54)雪界レ天」、又は「西望則逾二原野一而雪嶺界レ天」とある句は、蓋けだし実景をよんだもので、雪嶺或は西嶺は富士山を指したものに外なるまい。',
          translation:
            '以“静胜轩”为题的诗文里所说“西岭当窗雪界天”之类的句子，大概确实是对实景的描写，其中的“雪岭”或“西岭”无疑就是指富士山。',
          tokens: [
            { surface: '静勝軒', lemma: '静勝軒', reading: 'セイショウケン', furigana: 'せいしょうけん', pos: '名詞', meaning: '静胜轩' },
            { surface: 'を題として', lemma: '題とする', reading: 'ヲダイトシテ', furigana: 'をだいとして', pos: '動詞', meaning: '以……为题', conjugation: { type: 'サ変', form: '連用形A' } },
            { surface: '記述した詩文', lemma: '記述した詩文', reading: 'キジュツシタシブン', furigana: 'きじゅつしたしぶん', pos: '名詞', meaning: '相关诗文' },
            { surface: 'に', lemma: 'に', reading: 'ニ', furigana: 'に', pos: '助詞', meaning: '对象助词' },
            { surface: '「西嶺当レ※雪界レ天」', lemma: '西嶺当レ※雪界レ天', reading: 'セイレイトウレソウセツカイレテン', furigana: 'せいれいとうれそうせつかいれてん', pos: '名詞', meaning: '引文一' },
            { surface: '、', lemma: '、', reading: '、', furigana: '、', pos: '接尾辞', meaning: '顿号' },
            { surface: '又は', lemma: '又は', reading: 'マタハ', furigana: 'または', pos: '接続詞', meaning: '或者' },
            { surface: '「西望則逾二原野一而雪嶺界レ天」', lemma: '西望則逾二原野一而雪嶺界レ天', reading: 'セイボウソクユゲンヤジセツレイカイレテン', furigana: 'せいぼうそくげんやをこえてせつれいかいれてん', pos: '名詞', meaning: '引文二' },
            { surface: 'とある句', lemma: 'とある句', reading: 'トアルク', furigana: 'とあるく', pos: '名詞', meaning: '这些句子' },
            { surface: 'は', lemma: 'は', reading: 'ハ', furigana: 'は', pos: '助詞', meaning: '主题助词' },
            { surface: '蓋けだし', lemma: '蓋し', reading: 'ケダシ', furigana: 'けだし', pos: '副詞', meaning: '大概，想必' },
            { surface: '実景をよんだ', lemma: 'よむ', reading: 'ジッケイヲヨンダ', furigana: 'じっけいをよんだ', pos: '動詞', meaning: '描写实景', conjugation: { type: '五段', form: '連体形' } },
            { surface: 'もので', lemma: 'もの', reading: 'モノデ', furigana: 'もので', pos: '名詞', meaning: '构成说明语气' },
            { surface: '、', lemma: '、', reading: '、', furigana: '、', pos: '接尾辞', meaning: '顿号' },
            { surface: '雪嶺或は西嶺', lemma: '雪嶺或は西嶺', reading: 'セツレイアルイハセイレイ', furigana: 'せつれいあるいはせいれい', pos: '名詞', meaning: '雪岭或西岭' },
            { surface: 'は', lemma: 'は', reading: 'ハ', furigana: 'は', pos: '助詞', meaning: '主题助词' },
            { surface: '富士山', lemma: '富士山', reading: 'フジサン', furigana: 'ふじさん', pos: '名詞', meaning: '富士山' },
            { surface: 'を指した', lemma: '指す', reading: 'ヲサシタ', furigana: 'をさした', pos: '動詞', meaning: '指代', conjugation: { type: '五段', form: '連体形' } },
            { surface: 'ものに外なら', lemma: '外ならぬ', reading: 'モノニホカナラ', furigana: 'ものにほかなら', pos: '名詞', meaning: '无非就是' },
            { surface: 'まい', lemma: 'まい', reading: 'マイ', furigana: 'まい', pos: '助動詞', meaning: '推量否定，表示“不会不是”', conjugation: { type: '形容動詞', form: '終止形' } },
            { surface: '。', lemma: '。', reading: '。', furigana: '。', pos: '接尾辞', meaning: '句号' },
          ],
          grammarTips: [
            { point: '〜に外ならない', description: '书面强断定，表示“无非就是……”“正是……”。', difficulty: 'intermediate', tokenIndices: [18, 19] },
            { point: '蓋し', description: '古风副词，用于推量或判断，语气近似“想来”“大概”。', difficulty: 'advanced', tokenIndices: [10] },
          ],
          dependencyTree: {
            text: '诗句所指对象的判断',
            tokenIndices: Array.from({ length: 21 }, (_, index) => index),
            relation: 'root',
            children: [
              { text: '静勝軒を題として記述した詩文に', tokenIndices: [0, 1, 2, 3], relation: 'advmod', children: [] },
              { text: '引用句群とある句は', tokenIndices: [4, 6, 7, 8, 9], relation: 'nsubj', children: [] },
              { text: '蓋けだし実景をよんだもので', tokenIndices: [10, 11, 12], relation: 'conj', children: [] },
              { text: '雪嶺或は西嶺は富士山を指した', tokenIndices: [14, 15, 16, 17], relation: 'conj', children: [] },
              { text: 'ものに外ならまい', tokenIndices: [18, 19], relation: 'aux', children: [] },
              { text: '。', tokenIndices: [20], relation: 'punct', children: [] },
            ],
          },
        },
        {
          originalText:
            '道灌は風流二千石といわれた程あって、歌も上手によみ、扇谷の老臣として軍旅に忙しい身でありながら、よくこの静勝軒で歌合や連歌の会などを催した。',
          translation:
            '道灌素有“风流二千石”之称，和歌也写得很好；虽然作为扇谷家的老臣忙于军旅，却仍常在静胜轩举办歌合与连歌会。',
          tokens: [
            { surface: '道灌', lemma: '道灌', reading: 'ドウカン', furigana: 'どうかん', pos: '名詞', meaning: '太田道灌' },
            { surface: 'は', lemma: 'は', reading: 'ハ', furigana: 'は', pos: '助詞', meaning: '主题助词' },
            { surface: '風流二千石', lemma: '風流二千石', reading: 'フウリュウニセンゴク', furigana: 'ふうりゅうにせんごく', pos: '名詞', meaning: '风流二千石，赞誉其风雅' },
            { surface: 'といわれた', lemma: 'いう', reading: 'トイワレタ', furigana: 'といわれた', pos: '動詞', meaning: '被称为', conjugation: { type: '一段', form: '連体形' } },
            { surface: '程あって', lemma: '程ある', reading: 'ホドアッテ', furigana: 'ほどあって', pos: '名詞', meaning: '达到那种程度' },
            { surface: '、', lemma: '、', reading: '、', furigana: '、', pos: '接尾辞', meaning: '顿号' },
            { surface: '歌も', lemma: '歌', reading: 'ウタモ', furigana: 'うたも', pos: '名詞', meaning: '和歌也' },
            { surface: '上手によみ', lemma: 'よむ', reading: 'ジョウズニヨミ', furigana: 'じょうずによみ', pos: '動詞', meaning: '善于吟咏', conjugation: { type: '五段', form: '連用形A' } },
            { surface: '、', lemma: '、', reading: '、', furigana: '、', pos: '接尾辞', meaning: '顿号' },
            { surface: '扇谷の老臣として', lemma: '老臣', reading: 'オウギガヤツノロウシントシテ', furigana: 'おうぎがやつのろうしんとして', pos: '名詞', meaning: '作为扇谷家的老臣' },
            { surface: '軍旅に忙しい', lemma: '忙しい', reading: 'グンリョニイソガシイ', furigana: 'ぐんりょにいそがしい', pos: '形容詞', meaning: '忙于军旅', conjugation: { type: '形容詞', form: '連体形' } },
            { surface: '身でありながら', lemma: 'でありながら', reading: 'ミデアリナガラ', furigana: 'みでありながら', pos: '助動詞', meaning: '虽然身处……', conjugation: { type: '形容動詞', form: '連用形A' } },
            { surface: '、', lemma: '、', reading: '、', furigana: '、', pos: '接尾辞', meaning: '顿号' },
            { surface: 'よく', lemma: 'よく', reading: 'ヨク', furigana: 'よく', pos: '副詞', meaning: '经常' },
            { surface: 'この静勝軒で', lemma: 'この静勝軒', reading: 'コノセイショウケンデ', furigana: 'このせいしょうけんで', pos: '名詞', meaning: '在这静胜轩' },
            { surface: '歌合や連歌の会', lemma: '歌合や連歌の会', reading: 'ウタアワセヤレンガノカイ', furigana: 'うたあわせやれんがのかい', pos: '名詞', meaning: '歌合与连歌会' },
            { surface: 'などを', lemma: 'など', reading: 'ナドヲ', furigana: 'などを', pos: '助詞', meaning: '等，表示列举' },
            { surface: '催した', lemma: '催す', reading: 'モヨオシタ', furigana: 'もよおした', pos: '動詞', meaning: '举办', conjugation: { type: '五段', form: '終止形' } },
            { surface: '。', lemma: '。', reading: '。', furigana: '。', pos: '接尾辞', meaning: '句号' },
          ],
          grammarTips: [
            { point: '〜ながら', description: '逆接让步，表示“虽然……却……”。', difficulty: 'beginner', tokenIndices: [10, 11] },
            { point: '〜など', description: '用于列举同类事项，表达“……之类”。', difficulty: 'beginner', tokenIndices: [15, 16] },
          ],
          dependencyTree: {
            text: '道灌的风流素养与活动',
            tokenIndices: Array.from({ length: 19 }, (_, index) => index),
            relation: 'root',
            children: [
              { text: '道灌は風流二千石といわれた程あって', tokenIndices: [0, 1, 2, 3, 4], relation: 'nsubj', children: [] },
              { text: '歌も上手によみ', tokenIndices: [6, 7], relation: 'conj', children: [] },
              { text: '扇谷の老臣として軍旅に忙しい身でありながら', tokenIndices: [9, 10, 11], relation: 'advmod', children: [] },
              { text: 'よくこの静勝軒で歌合や連歌の会などを催した', tokenIndices: [13, 14, 15, 16, 17], relation: 'conj', children: [] },
              { text: '。', tokenIndices: [18], relation: 'punct', children: [] },
            ],
          },
        },
        {
          originalText:
            '元より泊船亭や含雪斎の名は、「※(「窗／心」、第3水準1-89-54)含二西嶺千秋雪一、門泊二東呉万里船一」という詩句から取ったものであろうが、当時の江戸城は今の宮城内に在る元の本丸の地であったということであるから、眺望の広闊なることは言う迄もないことで、富士は更なり遠い赤石山脈の悪沢わるさわ岳や荒川岳（塩見岳）の七月上旬に於ける残雪は、恐らく含雪斎の主人公をして、西嶺千秋雪の感を深からしめたことであろうと思う。',
          translation:
            '泊船亭与含雪斋之名固然来自“窗含西岭千秋雪，门泊东吴万里船”的诗句；而彼时江户城位于旧本丸，视野极为开阔，因此不仅富士山，就连更远的赤石山脉残雪，也大概会让含雪斋之主更深切地感到“西岭千秋雪”的意味。',
          tokens: [
            { surface: '元より', lemma: '元より', reading: 'モトヨリ', furigana: 'もとより', pos: '副詞', meaning: '本来，原本' },
            { surface: '泊船亭や含雪斎の名', lemma: '泊船亭や含雪斎の名', reading: 'ハクセンテイヤガンセツサイノナ', furigana: 'はくせんていやがんせつさいのな', pos: '名詞', meaning: '泊船亭与含雪斋之名' },
            { surface: 'は', lemma: 'は', reading: 'ハ', furigana: 'は', pos: '助詞', meaning: '主题助词' },
            { surface: '「※含二西嶺千秋雪一、門泊二東呉万里船一」', lemma: '詩句', reading: 'シク', furigana: 'しく', pos: '名詞', meaning: '所引诗句' },
            { surface: 'という詩句から', lemma: 'という詩句', reading: 'トイウシクカラ', furigana: 'というしくから', pos: '名詞', meaning: '出自该诗句' },
            { surface: '取った', lemma: '取る', reading: 'トッタ', furigana: 'とった', pos: '動詞', meaning: '取名于', conjugation: { type: '五段', form: '連体形' } },
            { surface: 'ものであろう', lemma: 'もの', reading: 'モノデアロウ', furigana: 'ものであろう', pos: '名詞', meaning: '大概是如此' },
            { surface: 'が', lemma: 'が', reading: 'ガ', furigana: 'が', pos: '助詞', meaning: '转折助词' },
            { surface: '、', lemma: '、', reading: '、', furigana: '、', pos: '接尾辞', meaning: '顿号' },
            { surface: '当時の江戸城', lemma: '当時の江戸城', reading: 'トウジノエドジョウ', furigana: 'とうじのえどじょう', pos: '名詞', meaning: '当时的江户城' },
            { surface: 'は', lemma: 'は', reading: 'ハ', furigana: 'は', pos: '助詞', meaning: '主题助词' },
            { surface: '今の宮城内に在る元の本丸の地', lemma: '本丸の地', reading: 'イマノキュウジョウナイニアルモトノホンマルノチ', furigana: 'いまのきゅうじょうないにあるもとのほんまるのち', pos: '名詞', meaning: '今皇居内旧本丸所在地' },
            { surface: 'であった', lemma: 'だ', reading: 'デアッタ', furigana: 'であった', pos: '助動詞', meaning: '过去判断', conjugation: { type: '形容動詞', form: '連体形' } },
            { surface: 'ということであるから', lemma: 'ということ', reading: 'トイウコトデアルカラ', furigana: 'ということであるから', pos: '名詞', meaning: '因为据说如此' },
            { surface: '、', lemma: '、', reading: '、', furigana: '、', pos: '接尾辞', meaning: '顿号' },
            { surface: '眺望の広闊なること', lemma: '眺望の広闊', reading: 'チョウボウノコウカツナルコト', furigana: 'ちょうぼうのこうかつなること', pos: '名詞', meaning: '视野广阔' },
            { surface: 'は言う迄もない', lemma: '言う迄もない', reading: 'ハイウマデモナイ', furigana: 'はいうまでもない', pos: '形容詞', meaning: '不言而喻', conjugation: { type: '形容詞', form: '終止形' } },
            { surface: 'ことで', lemma: 'こと', reading: 'コトデ', furigana: 'ことで', pos: '名詞', meaning: '承上启下' },
            { surface: '、', lemma: '、', reading: '、', furigana: '、', pos: '接尾辞', meaning: '顿号' },
            { surface: '富士は更なり', lemma: '更なり', reading: 'フジハサラナリ', furigana: 'ふじはさらなり', pos: '副詞', meaning: '富士自不必说' },
            { surface: '遠い赤石山脈の悪沢岳や荒川岳（塩見岳）', lemma: '赤石山脈', reading: 'トオイアカイシサンミャクノワルサワダケヤアラカワダケシオミダケ', furigana: 'とおいあかいしさんみゃくのわるさわだけやあらかわだけしおみだけ', pos: '名詞', meaning: '更远的赤石山脉诸峰' },
            { surface: 'の七月上旬に於ける残雪', lemma: '残雪', reading: 'ノシチガツジョウジュンニオケルザンセツ', furigana: 'のしちがつじょうじゅんにおけるざんせつ', pos: '名詞', meaning: '七月上旬的残雪' },
            { surface: 'は', lemma: 'は', reading: 'ハ', furigana: 'は', pos: '助詞', meaning: '主题助词' },
            { surface: '恐らく', lemma: '恐らく', reading: 'オソラク', furigana: 'おそらく', pos: '副詞', meaning: '恐怕，大概' },
            { surface: '含雪斎の主人公', lemma: '含雪斎の主人公', reading: 'ガンセツサイノシュジンコウ', furigana: 'がんせつさいのしゅじんこう', pos: '名詞', meaning: '含雪斋之主' },
            { surface: 'をして', lemma: 'をして', reading: 'ヲシテ', furigana: 'をして', pos: '助詞', meaning: '使令结构' },
            { surface: '西嶺千秋雪の感', lemma: '西嶺千秋雪の感', reading: 'セイレイセンシュウセツノカン', furigana: 'せいれいせんしゅうせつのかん', pos: '名詞', meaning: '“西岭千秋雪”的感受' },
            { surface: 'を深からしめた', lemma: '深からしめる', reading: 'ヲフカカラシメタ', furigana: 'をふかからしめた', pos: '動詞', meaning: '使其更加深刻', conjugation: { type: '一段', form: '連体形' } },
            { surface: 'ことであろう', lemma: 'こと', reading: 'コトデアロウ', furigana: 'ことであろう', pos: '名詞', meaning: '想必如此' },
            { surface: 'と思う', lemma: '思う', reading: 'トオモウ', furigana: 'とおもう', pos: '動詞', meaning: '我认为', conjugation: { type: '五段', form: '終止形' } },
            { surface: '。', lemma: '。', reading: '。', furigana: '。', pos: '接尾辞', meaning: '句号' },
          ],
          grammarTips: [
            { point: '〜までもない', description: '表示某事明显到无需再说，意为“不言而喻”。', difficulty: 'beginner', tokenIndices: [15, 16] },
            { point: '〜をして', description: '古风书面使役结构，可理解为“使……”。', difficulty: 'advanced', tokenIndices: [24, 25, 26, 27] },
            { point: '〜ことであろう', description: '书面推量判断，表示“想必……吧”。', difficulty: 'intermediate', tokenIndices: [28] },
          ],
          dependencyTree: {
            text: '名称出处与广阔眺望带来的诗意联想',
            tokenIndices: Array.from({ length: 31 }, (_, index) => index),
            relation: 'root',
            children: [
              { text: '元より泊船亭や含雪斎の名は詩句から取ったものであろう', tokenIndices: [0, 1, 2, 3, 4, 5, 6, 7], relation: 'conj', children: [] },
              { text: '当時の江戸城は今の宮城内に在る元の本丸の地であったということであるから', tokenIndices: [9, 10, 11, 12, 13], relation: 'advmod', children: [] },
              { text: '眺望の広闊なることは言う迄もない', tokenIndices: [15, 16, 17], relation: 'conj', children: [] },
              { text: '富士は更なり遠い赤石山脈...残雪は', tokenIndices: [19, 20, 21, 22], relation: 'nsubj', children: [] },
              { text: '恐らく含雪斎の主人公をして西嶺千秋雪の感を深からしめた', tokenIndices: [23, 24, 25, 26, 27], relation: 'conj', children: [] },
              { text: 'ことであろうと思う', tokenIndices: [28, 29], relation: 'aux', children: [] },
              { text: '。', tokenIndices: [30], relation: 'punct', children: [] },
            ],
          },
        },
      ],
    },
  ],
}

export const mockRawModelOutput = JSON.stringify(mockArticle, null, 2)
